server:
  port: 8083
  servlet:
    context-path: /gamer

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:gamerWeb.db
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration/
    sql-migration-prefix: gamerWeb
    sql-migration-suffixes: .sql
    sql-migration-separator: _
    validate-on-migrate: true
    baseline-on-migrate: true
    validate-migration-naming: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  mvc:
    static-path-pattern: /picture/**
  web:
    resources:
      static-locations: file:picture
logging:
  file:
    name: ./logs/info.log
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 10MB
sa-token:
  # token 名称 (同时也是cookie名称)
  token-name: token
  # token 有效期，30分钟
  timeout: 1800
  is-concurrent: true
  # token 临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 1800
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  is-print: false

picture.path: ./picture

default_username: admin
default_password: 123456



